package com.dmi.mobile.inspection.greendao;
// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Citations.
 */
public class Citation {

    private Long id;
    private String CitationUri;

    public Citation() {
    }

    public Citation(Long id) {
        this.id = id;
    }

    public Citation(Long id, String CitationUri) {
        this.id = id;
        this.CitationUri = CitationUri;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCitationUri() {
        return CitationUri;
    }

    public void setCitationUri(String CitationUri) {
        this.CitationUri = CitationUri;
    }

}
