package com.dmi.minesafety.demo.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.dmi.minesafety.demo.greendao.Citation;
import com.dmi.minesafety.demo.greendao.Event;
import com.dmi.minesafety.demo.greendao.Form;

import com.dmi.minesafety.demo.greendao.CitationDao;
import com.dmi.minesafety.demo.greendao.EventDao;
import com.dmi.minesafety.demo.greendao.FormDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig citationDaoConfig;
    private final DaoConfig eventDaoConfig;
    private final DaoConfig formDaoConfig;

    private final CitationDao citationDao;
    private final EventDao eventDao;
    private final FormDao formDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        citationDaoConfig = daoConfigMap.get(CitationDao.class).clone();
        citationDaoConfig.initIdentityScope(type);

        eventDaoConfig = daoConfigMap.get(EventDao.class).clone();
        eventDaoConfig.initIdentityScope(type);

        formDaoConfig = daoConfigMap.get(FormDao.class).clone();
        formDaoConfig.initIdentityScope(type);

        citationDao = new CitationDao(citationDaoConfig, this);
        eventDao = new EventDao(eventDaoConfig, this);
        formDao = new FormDao(formDaoConfig, this);

        registerDao(Citation.class, citationDao);
        registerDao(Event.class, eventDao);
        registerDao(Form.class, formDao);
    }
    
    public void clear() {
        citationDaoConfig.getIdentityScope().clear();
        eventDaoConfig.getIdentityScope().clear();
        formDaoConfig.getIdentityScope().clear();
    }

    public CitationDao getCitationDao() {
        return citationDao;
    }

    public EventDao getEventDao() {
        return eventDao;
    }

    public FormDao getFormDao() {
        return formDao;
    }

}
